name: complete_advanced_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  analyzer: ^6.4.1
  connectivity_plus: ^6.0.5
  country_code_picker: ^3.0.0
  dartz: ^0.10.1
  device_info: ^2.0.3
  dio: ^5.6.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  freezed: ^2.5.2
  get_it: ^7.7.0
  image_picker: ^1.1.2
  json_serializable: ^6.8.0
  lottie: ^3.1.2
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.2.0
  rxdart: ^0.28.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  retrofit_generator: ^8.2.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash_logo.png
    - assets/images/onboarding_logo1.svg
    - assets/images/onboarding_logo2.svg
    - assets/images/onboarding_logo3.svg
    - assets/images/onboarding_logo4.svg
    - assets/images/hollow_circle_ic.svg
    - assets/images/left_arrow_ic.svg
    - assets/images/right_arrow_ic.svg
    - assets/images/solid_circle_ic.svg
    - assets/images/logout_ic.svg
    - assets/json/loading.json
    - assets/json/error.json
    - assets/json/empty.json
    - assets/json/success.json

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300